// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yowgvnnnwllilneovaxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvd2d2bm5ud2xsaWxuZW92YXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjM3MTcsImV4cCI6MjA3MDgzOTcxN30.vojGIE7mBusklz1VB3kCr0R7DeTjswsgtH3WsA-rGA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});